name: Build container image

on:
  push:
    branches:
      - "test_ci"
#    paths:
#      - 'conf/**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y wget
      - name: Install Apptainer
        run : |
          wget https://github.com/apptainer/apptainer/releases/download/v1.1.0-rc.2/apptainer_1.1.0-rc.2_amd64.deb
          sudo apt-get install -y ./apptainer_1.1.0-rc.2_amd64.deb
      - uses: actions/checkout@v3
      - name: Check version
        run: |
          apptainer version
